// Package models defines the core domain types used across bb-hunter.
package models

import (
	"crypto/sha256"
	"fmt"
	"net/url"
	"sort"
	"strings"
	"time"
)

// Severity represents the severity level of a finding.
type Severity string

const (
	SeverityInfo     Severity = "info"
	SeverityLow      Severity = "low"
	SeverityMedium   Severity = "medium"
	SeverityHigh     Severity = "high"
	SeverityCritical Severity = "critical"
)

// FindingStatus tracks the lifecycle of a finding.
type FindingStatus string

const (
	StatusNew       FindingStatus = "new"       // just discovered by scanner
	StatusAnalyzed  FindingStatus = "analyzed"  // classified by Analyst
	StatusConfirmed FindingStatus = "confirmed" // verified by Verifier (Phase 2)
	StatusReported  FindingStatus = "reported"  // report generated by Reporter
	StatusApproved  FindingStatus = "approved"  // approved by human via HITL
	StatusSubmitted FindingStatus = "submitted" // submitted to BB platform
	StatusRejected  FindingStatus = "rejected"  // rejected by human
	StatusDuplicate FindingStatus = "duplicate" // duplicate of existing finding
)

// VulnClass is the vulnerability classification assigned by Analyst.
type VulnClass string

const (
	VulnXSS           VulnClass = "xss"
	VulnSQLi          VulnClass = "sqli"
	VulnSSRF          VulnClass = "ssrf"
	VulnIDOR          VulnClass = "idor"
	VulnAuthBypass    VulnClass = "auth_bypass"
	VulnInfoDisclosure VulnClass = "info_disclosure"
	VulnRCE           VulnClass = "rce"
	VulnLFI           VulnClass = "lfi"
	VulnOpenRedirect  VulnClass = "open_redirect"
	VulnCSRF          VulnClass = "csrf"
	VulnMisconfig     VulnClass = "misconfig"
	VulnOther         VulnClass = "other"
)

// Finding represents a discovered vulnerability through the entire pipeline.
type Finding struct {
	// Identity
	ID         string    `json:"id"`
	FindingKey string    `json:"finding_key"` // dedup key (normalized hash)
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`

	// Source
	ProgramID string `json:"program_id"`
	ScanRunID string `json:"scan_run_id"`

	// Location
	URL    string `json:"url"`
	Method string `json:"method"` // GET, POST, etc.
	Host   string `json:"host"`
	Path   string `json:"path"`

	// Scanner evidence
	NucleiTemplateID string   `json:"nuclei_template_id,omitempty"`
	ScannerEvidence  string   `json:"scanner_evidence,omitempty"` // raw scanner output
	Severity         Severity `json:"severity"`

	// Analyst classification (filled by Analyst agent)
	VulnClass  VulnClass `json:"vuln_class,omitempty"`
	Hypothesis string    `json:"hypothesis,omitempty"` // Analyst's reasoning
	Confidence float64   `json:"confidence,omitempty"` // 0.0-1.0

	// Status
	Status FindingStatus `json:"status"`

	// Report (filled by Reporter agent)
	ReportMarkdown string `json:"report_markdown,omitempty"`

	// HITL
	HITLDecision string    `json:"hitl_decision,omitempty"` // approve/reject reason
	HITLDecidedAt *time.Time `json:"hitl_decided_at,omitempty"`

	// Metadata
	ParamNames []string `json:"param_names,omitempty"` // sorted query/body parameter names
}

// ComputeFindingKey generates a normalized deduplication key.
// Key = sha256(method | normalized_host+path | sorted_params | template_id)
// Does NOT include status_code (flaps) per v4 critique §2.5.
func ComputeFindingKey(method, rawURL, nucleiTemplateID string, paramNames []string) string {
	u, err := url.Parse(rawURL)
	if err != nil {
		return fmt.Sprintf("unparseable:%s", rawURL)
	}

	// Normalize host: lowercase, strip port if default
	host := strings.ToLower(u.Hostname())

	// Normalize path: lowercase, strip trailing slash (except root)
	path := strings.ToLower(u.Path)
	if path != "/" {
		path = strings.TrimSuffix(path, "/")
	}

	// Sort param names for determinism
	sorted := make([]string, len(paramNames))
	copy(sorted, paramNames)
	sort.Strings(sorted)

	raw := fmt.Sprintf("%s|%s%s|%s|%s",
		strings.ToUpper(method),
		host,
		path,
		strings.Join(sorted, ","),
		nucleiTemplateID,
	)

	hash := sha256.Sum256([]byte(raw))
	return fmt.Sprintf("%x", hash[:16]) // 128-bit, hex-encoded
}

// ScanRun represents a single execution of the scanner pipeline.
type ScanRun struct {
	ID        string    `json:"id"`
	ProgramID string    `json:"program_id"`
	StartedAt time.Time `json:"started_at"`
	FinishedAt *time.Time `json:"finished_at,omitempty"`

	// Type of scan
	RunType string `json:"run_type"` // "full", "delta", "deep-dive"

	// Stats
	HostsScanned    int `json:"hosts_scanned"`
	URLsCrawled     int `json:"urls_crawled"`
	FindingsTotal   int `json:"findings_total"`
	FindingsNew     int `json:"findings_new"`
	FindingsDup     int `json:"findings_dup"`

	// Errors
	Errors []string `json:"errors,omitempty"`

	HasNewFindings bool `json:"has_new_findings"`
}
